system_packages:
  - createrepo
  - gcc
  - git
  - libffi-devel
  - mock
  - openssl-devel
  - policycoreutils
  - python-setuptools
  - python2-devel
  - redhat-rpm-config
  - rpmdevtools
  - yum-utils
